version: "3.10"

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
      - ./media:/app/media
    ports:
    - "8013:8013"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn config.wsgi:application -b 0.0.0.0:8013"
    env_file:
      - .env
    depends_on:
      - db
